project_id = "vrnjccybvrdzakrrfard"

[functions.chat]
verify_jwt = false

[functions.vapi-call]
verify_jwt = false

[functions.vapi-public-key]
verify_jwt = false

[functions.daily-room]
verify_jwt = false

[functions.create-vapi-assistants]
verify_jwt = false

[functions.create-vapi-assistants-retry]
verify_jwt = false

[functions.heygen-streaming]
verify_jwt = false

[functions.video-narration]
verify_jwt = false

[functions.generate-embeddings]
verify_jwt = false

[functions.session-analysis]
verify_jwt = false